### ISSUE TITLE
Malfunctioning of the directories.

### ISSUE THREAD

**Issue by alexb3d** [flathub/com.github.optyfr.JRomManager#15]
Hello.
I'm using the Flatpak version on Ubuntu 22.04.

When importing Dats, it has the MAME executable option, in game executables are saved in "/usr/games" but cannot be accessed.

Only the folders Downloads (as read-only) and Documents (read and write) are available. It is a bit inconvenient to have to move all the sets.

**Comment by FakeShemp** [comment]
Use flatseal for permissions.

https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by FakeShemp** [comment]
This is how flatpak works. You cannot exit the sandbox without giving it permission or portals.

If you want to do it without flatseal, it's  `--filesystem=path`

**Comment by alexb3d** [comment]
I understand.
It's going to be a real hassle to have to do this for Gimp, Blender, Kdenlive, OpenToonz, RetroArch, Flycast, etc...
Well, all of them. I have all the programs installed with Flatpak.

**Comment by FakeShemp** [comment]
I think all of those use Gnome or KDE file browser portals, so you won't need to do anything special.

**Comment by alexb3d** [comment]
Sorry to take up so much of your time, but if the other programs use a portals, why doesn't JRomManager?
