### ISSUE TITLE
The program crashes when the Cancel button is pressed.

### ISSUE THREAD

**Issue by alexb3d** [flathub/com.github.optyfr.JRomManager#16]
If the "destination folder" is deleted by mistake, a warning is displayed.
- Error
- dst dir is not a directory
Click on accept, it returns to the Progression window, and remains inert. 
If you close this window, the program crashes.

When I click on Scan, and cancel the Progression, an Error window comes up with no text. After that the program itself crashes.

**Comment by FakeShemp** [comment]
This seems like an upstream error. Does it only happen on the flatpak version?

**Comment by optyfr** [comment]
What is the version of JRomManager here?

**Comment by FakeShemp** [comment]
2.5.1

**Comment by optyfr** [comment]
ok... seems that https://flathub.org/apps/details/com.github.optyfr.JRomManager page is still stuck to 2.4.4

**Comment by alexb3d** [comment]
@FakeShemp I have only tried flathub.

**Comment by optyfr** [comment]
Anyway, version 3.0 which is a total rewrite in java fx, has the problem already fixed...
It'll be released when all will be ready and well tested.

**Comment by alexb3d** [comment]
I wait for the new version to come out and test it again, and also wait to test other bugs that I have not reported. 
Wonderful program and unique in Linux.
Thank you @optyfr
