### ISSUE TITLE
Gnome dark theme makes buttons unreadable

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.github.optyfr.JRomManager#5]
Having the dark theme of Gnome in use makes much of the tabs, buttons and text unreadable.

**Comment by optyfr** [comment]
Hello
Was it happening in 2.2.0? Does it mean that standard java swing theme is incompatible with this theme? Or something else?

**Comment by FakeShemp** [comment]
Yes, it is happening in 2.2.0 also. I don't know what is causing it. It might be a flatpak issue.
